library(httr)
library(jsonlite)
library(knitr)
library(dplyr)
library(jpeg)
library(ggplot2)
library(plotly)
library(shiny)
source("ui.R")
source("server.R")

shinyApp(ui = shinyUI(ui), server = shinyServer(server))